# Generated by Django 6.1.1 on 2026-09-21 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='post_not_empty',
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('body', ''), _negated=True), models.Q(('image', ''), _negated=True), _connector='OR'), name='post_not_empty'),
        ),
    ]
